### ISSUE TITLE
CloudFront distribution has a hardcoded DefaultTTL of 30 seconds

### ISSUE THREAD

**Issue by bs-thomas** [venveo/serverless-sharp#49]
I noticed that the CloudFront distribution has a hardcoded DefaultTTL of 30 seconds.  Wondering if that is intentional?  Sounds odd to use 30 seconds as the default TTL

```
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Comment: Cloudfront distribution for serverless image handler
          DefaultCacheBehavior:
            TargetOriginId: ApiGateway
            ViewerProtocolPolicy: 'redirect-to-https'
            DefaultTTL: 30
            ForwardedValues:
              Headers:
                - 'Accept'
              QueryString: true
          Enabled: true
          Origins:
            - Id: ApiGateway
              DomainName:
                Fn::Join:
                  - "."
                  - - Ref: ApiGatewayRestApi
                    - execute-api.${self:custom.settings.region}.amazonaws.com
              OriginPath: "/${self:provider.stage}"
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
```
