### ISSUE TITLE
Selected region issue

### ISSUE THREAD

**Issue by gregBerthelot** [venveo/serverless-sharp#53]
Hi,

Despite `region: 'eu-west-3'` in settings.yml it is always deployed in us-east-1 region. Here is my settings:

```
defaults: &defaults
  serviceName: serverlessImageHandler
  offlinePort: 80
  region: 'eu-west-3'
  environment: &defaults.environment
    DEFAULT_QUALITY: 75
    DEFAULT_COMPRESS_QUALITY: 45
    SLS_IGNORE: favicon.ico
    MAX_IMAGE_WIDTH: 2000
    MAX_IMAGE_HEIGHT: 1000
    PNGQUANT_SPEED: 10

stages:
  prod:
    <<: *defaults
    environment:
      <<: *defaults.environment
      SOURCE_BUCKET: 'foo.bar/'
```

I have already one dev stage deployed in this region. Serverless log we an see wrong region:

```
Service Information
service: serverlessImageHandler
stage: prod
region: us-east-1
stack: serverlessImageHandler-prod
resources: 13
```

Any help would be appreciated
Cheers
Greg

**Comment by bs-thomas** [comment]
I believe you mean your CloudFormation template is created under us-east-1?

In your serverless.yml, between "runtime" and "stage" (under provider), add this line of code:

`region: ${self:custom.settings.region}`

Looks something like this:

```
provider:
  name: aws
  runtime: nodejs10.x
  region: ${self:custom.settings.region}
  stage: ${opt:stage,'dev'}
```

See if that solves your issue?
